apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-gcp
spec:
  acme:
    email: dogfood@tetrate.io
    privateKeySecretRef:
      name: letsencrypt-prod-gcp
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        cloudDNS:
          project: dogfood-cx