{{- $secrets := default dict .Values.secrets}}
{{- if $secrets.azure }}
apiVersion: v1
kind: Secret
metadata:
  name: azure-credentials
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.secrets.keep" . | indent 4}}
type: Opaque
data:
  client-secret: {{ required "secrets.azure.clientSecret" $secrets.azure.clientSecret | b64enc | quote }}
{{- end }}
