apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
{{ include "common.management-plane.operatorLabels" . | indent 4 }}
{{ include "common.labels" . | indent 4 }}
  name: tsb-operator-management-plane-{{ .Release.Namespace }}
rules:

# tsb groups
- apiGroups:
  - install.xcp.tetrate.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - install.tetrate.io
  resources:
  - '*'
  verbs:
  - '*'

# istio groups
- apiGroups:
  - authentication.istio.io
  - config.istio.io
  - install.istio.io
  - networking.istio.io
  - rbac.istio.io
  - security.istio.io
  - telemetry.istio.io
  resources:
  - '*'
  verbs:
  - '*'

# k8s groups
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions.apiextensions.k8s.io
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - apps
  - extensions
  - batch
  resources:
  - daemonsets
  - deployments
  - deployments/finalizers
  - deployments/scale
  - ingresses
  - replicasets
  - statefulsets
  - cronjobs
  - jobs
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  - certificatesigningrequests/approval
  verbs:
  - '*'
- apiGroups:
    - certificates.k8s.io
  resourceNames:
    - kubernetes.io/legacy-unknown
  resources:
    - signers
  verbs:
    - approve
    - sign
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - roles
  - rolebindings
  verbs:
  - '*'
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - configmaps
  - endpoints
  - events
  - namespaces
  - pods
  - pods/log
  - persistentvolumeclaims
  - secrets
  - secrets/finalizers
  - services
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - '*'
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - create
  - update

# cert-manager groups
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  - certificates
  - clusterissuers
  verbs:
  - '*'

## Needed in order to create the SCC in OpenShift
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - get
  - list
  - watch
  - create

- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  resourceNames:
  - tsb-controlplane
  - tsb-managementplane
  verbs:
  - update
  - patch
  - delete

## Needed in order to create the network-attachment-definitions in OpenShift
- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  verbs:
  - get
  - list
  - watch
  - create

- apiGroups:
  - k8s.cni.cncf.io
  resources:
  - network-attachment-definitions
  resourceNames:
  - istio-cni
  verbs:
  - update
  - patch
  - delete
- apiGroups:
  - kubegres.reactive-tech.io
  resources:
  - kubegres
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
