{{- $operator := default dict .Values.operator }}
{{- $deployment := default dict $operator.deployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
{{ include "common.management-plane.operatorLabels" . | indent 4 }}
{{ include "common.labels" . | indent 4 }}
{{- if $deployment.annotations }}
  annotations:
{{ toYaml $deployment.annotations | indent 4 }}
{{- end }}
  name: tsb-operator-management-plane
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ default 1 $deployment.replicaCount }}
{{- if $deployment.strategy }}
  strategy:
{{ toYaml $deployment.strategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      name: tsb-operator
  template:
    metadata:
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
{{- if $deployment.podAnnotations }}
{{ toYaml $deployment.podAnnotations | indent 8 }}
{{- end }}
      labels:
        name: tsb-operator
    spec:
{{- if $deployment.affinity }}
      affinity:
{{ toYaml $deployment.affinity | indent 8 }}
{{- end }}
{{- if $deployment.tolerations }}
      tolerations:
{{ toYaml $deployment.tolerations | indent 6 }}
{{- end }}
{{- if $deployment.podSecurityContext }}
      securityContext:
{{ toYaml $deployment.podSecurityContext | indent 8 }}
{{- end }}
      containers:
        - args:
            - management-plane
            - --deployment-name
            - tsb-operator-management-plane
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: OPERATOR_NAME
              value: tsb-operator
{{- if $deployment.env }}
{{ toYaml $deployment.env | indent 12 }}
{{- end }}
          image: '{{ required "image.registry" .Values.image.registry }}/tsboperator-server:{{ required "image.tag" .Values.image.tag }}'
          imagePullPolicy: {{ default "IfNotPresent" .Values.image.pullPolicy | quote }}
          name: tsb-operator
          resources:
{{ toYaml (default (include "common.management-plane.default.resources" . | fromYaml) $deployment.resources) | indent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
{{ include "livenessProbe" . | indent 10 }}
{{ include "readinessProbe" . | indent 10 }}
{{- if $deployment.containerSecurityContext }}
          securityContext:
{{ toYaml $deployment.containerSecurityContext | indent 12 }}
{{- end }}
      serviceAccountName: tsb-operator-management-plane
      volumes:
        - emptyDir: {}
          name: tmp
