{{- $operator := default dict .Values.operator }}
{{- if or $operator.pullSecret $operator.pullUsername }}
apiVersion: v1
data:
{{- if $operator.pullSecret }}
  .dockerconfigjson: "{{ $operator.pullSecret | b64enc }}"
{{- else if $operator.pullUsername }}
  .dockerconfigjson: "{{ include "common.dockerAuthJSON" . | b64enc }}"
{{- end }}
kind: Secret
metadata:
  name: "tsb-image-pull-secret"
  namespace: "{{ .Release.Namespace }}"
  labels:
{{ include "common.management-plane.operatorLabels" . | indent 4 }}
{{ include "common.labels" . | indent 4 }}
type: kubernetes.io/dockerconfigjson
{{ end }}
