{{- $operator := default dict .Values.operator }}
{{- $serviceAccount := default dict $operator.serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
{{ include "common.management-plane.operatorLabels" . | indent 4 }}
{{ include "common.labels" . | indent 4 }}
{{- if $serviceAccount.annotations }}
  annotations:
{{ toYaml $serviceAccount.annotations | indent 4 }}
{{- end }}
  name: tsb-operator-management-plane
  namespace: {{ .Release.Namespace | quote }}
{{- if or $operator.pullSecret $operator.pullUsername $serviceAccount.imagePullSecrets }}
imagePullSecrets:
{{- if or $operator.pullSecret $operator.pullUsername }}
  - name: "tsb-image-pull-secret"
{{- end }}
{{- range $serviceAccount.imagePullSecrets }}
  - name: {{ . | quote }}
{{- end }}
{{- end }}
