{{- $secrets := default dict .Values.secrets}}
{{- $tsbsecrets := default dict $secrets.tsb}}
{{- if $secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: admin-credentials
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.secrets.keep" . | indent 4}}
type: Opaque
data:
{{- if eq (.Values.spec).flavor "TSE" }}
{{/* this password will be used by the TSE container and invalidated after succeed */}}
  admin: {{ "tse-bootstrap-09" | sha256sum | b64enc | quote }}
{{- else }}
  admin: {{ required "secrets.tsb.adminPassword" $tsbsecrets.adminPassword | sha256sum | b64enc | quote }}
{{- end }}
{{- end }}
{{- if $tsbsecrets.cert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: tsb-certs
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.secrets.keep" . | indent 4}}
type: kubernetes.io/tls
data:
  {{/* check for secrets.tsb.ca and generate the cert and the key if given */}}
  tls.crt: {{ required "secrets.tsb.cert" $tsbsecrets.cert | b64enc | quote }}
  tls.key: {{ required "secrets.tsb.key" $tsbsecrets.key | b64enc | quote }}
{{- end }}
