{{- /*
  This will create the proper certificate and secret used by XCP central for sTLS.

  This requires cert manager to be previously installed in the environment.
*/}}
{{- if .Values.secrets }}
{{ if .Values.secrets.xcp }}
{{- $xcpAuthMode := include "getXCPauthModesYAML" . | fromYaml }}
{{- if .Values.secrets.xcp.autoGenerateCerts }}
{{/*TODO require cert-mananger*/}}
{{- $certManager := default dict .Values.certManager }}
{{- $certManagerNs := default "cert-manager" $certManager.clusterResourceNamespace}}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: xcp-trust-anchor
  namespace: {{ $certManagerNs | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.secrets.keep" . | indent 4}}
data:
  tls.crt: {{ required "secrets.xcp.rootca" .Values.secrets.xcp.rootca | b64enc | quote }}
  tls.key: {{ required "secrets.xcp.rootcakey" .Values.secrets.xcp.rootcakey | b64enc | quote }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: xcp-trust-anchor
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.secrets.keep" . | indent 4}}
spec:
  ca:
    secretName: xcp-trust-anchor
---
# to create root CA
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xcp-identity-issuer
  namespace: {{ $certManagerNs | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.secrets.keep" . | indent 4}}
spec:
  secretName: xcp-identity-issuer
  issuerRef:
    name: xcp-trust-anchor
    kind: ClusterIssuer
  duration: 30000h
  isCA: true
  commonName: ca.xcp.tetrate.io
  uris:
  - spiffe://xcp.tetrate.io/ca
  usages:
  - cert sign
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: xcp-identity-issuer
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.secrets.keep" . | indent 4}}
spec:
  ca:
    secretName: xcp-identity-issuer
---
{{ $xcpCentral := default dict .Values.secrets.xcp.central}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xcp-central-cert
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.secrets.keep" . | indent 4}}
spec:
  secretName: xcp-central-cert
  issuerRef:
    name: xcp-identity-issuer
    kind: ClusterIssuer
  duration: 30000h
  isCA: false
  dnsNames:
  - "central.xcp.tetrate.io"
  {{- range $xcpCentral.additionalDNSNames }}
  - {{ . | quote }}
  {{- end }}
  uris:
  {{- range $xcpCentral.additionalURIs }}
  - {{ . | quote }}
  {{- end }}
  {{- if $xcpCentral.additionalIPAddresses }}
  ipAddresses:
  {{ range $xcpCentral.additionalIPAddresses }}
  - {{ . | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
