{{- /*
  Creates the proper secret containing the certs for simpleTLS exposed by XCP Central.
  Also MPC will mount this to use CA cert to verify TLS certs presented by central in case of
  selfSigned.
*/}}
{{- if .Values.secrets }}
{{- if .Values.secrets.xcp }}
{{- $xcpCentral := default dict .Values.secrets.xcp.central }}
{{- if not .Values.secrets.xcp.autoGenerateCerts }}
apiVersion: v1
kind: Secret
metadata:
  name: xcp-central-cert
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "common.labels" . | indent 4 }}
  annotations:
{{ include "common.secrets.keep" . | indent 4}}
type: Opaque
data:
  {{- if .Values.secrets.xcp.rootca }}
  ca.crt: {{ .Values.secrets.xcp.rootca | b64enc | quote }}
  {{- end }}
  tls.crt: {{ required ".secrets.xcp.central.cert" $xcpCentral.cert | b64enc | quote }}
  tls.key: {{ required ".secrets.xcp.central.key" $xcpCentral.key | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}
