commonName: ""
certificates:
  issuer: "letsencrypt-prod-gcp"
tetrate-managementplane:
  image:
    registry: us-east1-docker.pkg.dev/dogfood-cx/registryrepository
    tag: 1.9.1
  spec:
    certIssuer:
      clusterIntermediateCAs: {}
      selfSigned: {}
    components:
      frontEnvoy:
        port: 443
    hub: us-east1-docker.pkg.dev/dogfood-cx/registryrepository
    organization: tetrate