commonName: ""
certificates:
  tsb:
    issuer: "selfsigned-ca"
  xcp:
    issuer: "selfsigned-ca"
tetrateManagementPlane:
  image:
    registry: us-east1-docker.pkg.dev/dogfood-cx/registryrepository
    tag: 1.12.5-internal-rc4
  spec:
    certIssuer:
      clusterIntermediateCAs: {}
      selfSigned: {}
    hub: us-east1-docker.pkg.dev/dogfood-cx/registryrepository
    organization: tetrate
    enableWasmDownloadProxy: true 
    dataStore:
      auditLogsCleanupRetention: 168h
      embeddedPostgres:
        tlsCertDuration: 8760h
        tlsCertRenewBefore: 720h
        tlsCaDuration: 87600h
        tlsCaRenewBefore: 7200h
    components:
      gitops:
        enabled: true
        reconcileInterval: 900s
        pushMode: ASYNC
      internalCertProvider:
        certManager:
          managed: AUTO
      frontEnvoy:
        port: 443
      oap:
        spmAgentReceiverEnabled: true
        streamingLogEnabled: true
      webUI:
        kubeSpec:
          overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: web
            patches:
            - path: spec.template.spec.containers.[name:web].env[-1]
              value:
                name: SESSION_AGE_IN_MINUTES
                value: "60"
  operator:
    deletionProtection: disabled
