commonName: ""
certificates:
  tsb:
    issuer: "selfsigned-ca"
  xcp:
    issuer: "selfsigned-ca"
tetrateManagementPlane:
  image:
    registry: us-east1-docker.pkg.dev/dogfood-cx/registryrepository
    tag: 1.10.2
  spec:
    certIssuer:
      clusterIntermediateCAs: {}
      selfSigned: {}
    hub: us-east1-docker.pkg.dev/dogfood-cx/registryrepository
    organization: tetrate
    enableWasmDownloadProxy: true 
    components:
      gitops:
        enabled: true
        reconcileInterval: 600s
        pushMode: ASYNC
      internalCertProvider:
        certManager:
          managed: AUTO
      frontEnvoy:
        port: 443
      oap:
        streamingLogEnabled: true
      webUI:
        kubeSpec:
          overlays:
          - apiVersion: apps/v1
            kind: Deployment
            name: web
            patches:
            - path: spec.template.spec.containers.[name:web].env[-1]
              value:
                name: SESSION_AGE_IN_MINUTES
                value: "60"
