---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tsb-certs
  namespace: tsb
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "100"
spec:
  duration: 2160h
  isCA: false
  issuerRef:
    name: "{{ .Values.certificates.issuer }}"
    kind: ClusterIssuer
  renewBefore: 720h
  secretName: tsb-certs
  commonName: "{{ .Values.commonName }}"
  dnsNames:
  - "{{ .Values.commonName }}"
  usages:
  - server auth
--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xcp-central-cert
  namespace: tsb
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "200"
spec:
  duration: 2160h
  isCA: false
  issuerRef:
    name: "{{ .Values.certificates.issuer }}"
    kind: ClusterIssuer
  renewBefore: 720h
  secretName: xcp-central-cert
  commonName: "{{ .Values.commonName }}"
  dnsNames:
  - "{{ .Values.commonName }}"
  usages:
  - server auth