apiVersion: v1
data:
  config.yaml: |
    clusterIdentifier: {{ .Values.clusterIdentifier }}
    clusterGeoTag: {{ .Values.clusterGeoTag }}
    allClustersInLocalGeoTag: {{ .Values.allClustersInLocalGeoTag }}
    allClustersGeoTags: {{ .Values.allClustersGeoTags }}
    globalDNSZone: {{ .Values.globalDNSZone }}
    localDNSZone: {{ .Values.localDNSZone }}
    reconcileRequeueSeconds: {{ .Values.reconcileRequeueSeconds }}
    localTXTRecordHealthyDurationSeconds: {{ .Values.localTXTRecordHealthyDurationSeconds }}
    globalTXTRecordHealthyDurationSeconds: {{ .Values.globalTXTRecordHealthyDurationSeconds }}
    txtRecordsTTLSeconds: {{ .Values.txtRecordsTTLSeconds }}
    cnameRecordsTTLSeconds: {{ .Values.cnameRecordsTTLSeconds }}
    aRecordsTTLSeconds: {{ .Values.aRecordsTTLSeconds }}
    selfHealInterval: {{ .Values.selfHealInterval }}
kind: ConfigMap
metadata:
  name: {{ include "tetrate-gslb.fullname" . }}-config
  namespace: {{ .Release.Namespace | quote }}
