{{ if .Values.serviceMonitor.enabled }}
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tetrate-gslb.fullname" . }}-metrics-monitor
  namespace: {{ .Release.Namespace | quote }}
spec:
  endpoints:
    - path: /metrics
      port: http
      scheme: http
  selector:
    matchLabels:
      {{- include "tetrate-gslb.selectorLabels" . | nindent 6 }}
{{- end }}