apiVersion: v1
kind: Service
metadata:
  name: {{ include "tetrate-gslb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "tetrate-gslb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: ext-dns-readiness
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: metrics
  selector:
    {{- include "tetrate-gslb.selectorLabels" . | nindent 4 }}
