apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "tetrate-gslb.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "tetrate-gslb.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "tetrate-gslb.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
