apiVersion: v1
kind: ConfigMap 
metadata:
  name: init-db-script 
  labels:
    app: postgres
data:
{{ (.Files.Glob "foo/*.sql").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: users
  labels:
    app: ssh
data:
  user-list-yaml: |
{{ .Values.users | toYaml | indent 4 }}