apiVersion: v1
kind: ConfigMap 
metadata:
  name: init-db-script 
  labels:
    app: postgres
data:
{{ (.Files.Glob "foo/*.sql").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: guacamole-configuration 
  labels:
    app: postgres
data:
{{ (.Files.Glob "foo/*.xml").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap 
metadata:
  name: ssh-users
  labels:
    app: ssh
data:
{{ (.Files.Glob "foo/*.ssh").AsConfig | indent 2 }}
