apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  labels:
    app: postgres
spec:
  storageClassName: {{ .Values.storageClass }}  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storageSize }} 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jumpbox-data 
  labels:
    app: ssh
spec:
  storageClassName: {{ .Values.storageClass }}  
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jumpbox.storageSize }} 
