apiVersion: v1
kind: Secret 
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  postgres_db: {{ default "" .Values.postgres.db | b64enc | quote }}
  postgres_user: {{ default "" .Values.postgres.user | b64enc | quote }}
  postgres_password: {{ default "" .Values.postgres.password | b64enc | quote }}

