{{- if .Values.components.fineract }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fineract.serviceAccount.name | default (printf "%s-sa" .Values.fineract.name) }}
  namespace: {{ include "dynabank.namespace" . }}
  labels:
    {{- include "dynabank.labels" . | nindent 4 }}
    app.kubernetes.io/component: core-banking
  {{- with .Values.fineract.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.components.transactionApi }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.transactionApi.serviceAccount.name | default (printf "%s-sa" .Values.transactionApi.name) }}
  namespace: {{ include "dynabank.namespace" . }}
  labels:
    {{- include "dynabank.labels" . | nindent 4 }}
    app.kubernetes.io/component: transaction-api
  {{- with .Values.transactionApi.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.components.fraudService }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.fraudService.serviceAccount.name | default (printf "%s-sa" .Values.fraudService.name) }}
  namespace: {{ include "dynabank.namespace" . }}
  labels:
    {{- include "dynabank.labels" . | nindent 4 }}
    app.kubernetes.io/component: fraud-service
  {{- with .Values.fraudService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.components.notificationService }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.notificationService.serviceAccount.name | default (printf "%s-sa" .Values.notificationService.name) }}
  namespace: {{ include "dynabank.namespace" . }}
  labels:
    {{- include "dynabank.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification-service
  {{- with .Values.notificationService.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.components.webPortal }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.webPortal.serviceAccount.name | default (printf "%s-sa" .Values.webPortal.name) }}
  namespace: {{ include "dynabank.namespace" . }}
  labels:
    {{- include "dynabank.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-portal
  {{- with .Values.webPortal.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.components.mariadb }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.mariadb.serviceAccount.name | default (printf "%s-sa" .Values.mariadb.name) }}
  namespace: {{ include "dynabank.namespace" . }}
  labels:
    {{- include "dynabank.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  {{- with .Values.mariadb.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.components.redis }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.redis.serviceAccount.name | default (printf "%s-sa" .Values.redis.name) }}
  namespace: {{ include "dynabank.namespace" . }}
  labels:
    {{- include "dynabank.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
  {{- with .Values.redis.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
---
{{- if .Values.components.kafka }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kafka.serviceAccount.name | default (printf "%s-sa" .Values.kafka.name) }}
  namespace: {{ include "dynabank.namespace" . }}
  labels:
    {{- include "dynabank.labels" . | nindent 4 }}
    app.kubernetes.io/component: messaging
  {{- with .Values.kafka.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
