---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dogfood-backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dogfood-backstage
  template:
    metadata:
      labels:
        app: dogfood-backstage
    spec:
      containers:
        - name: backstage
          image: us-east1-docker.pkg.dev/dogfood-cx/registryrepository/dogfood-backstage:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 7007
---
apiVersion: v1
kind: Service
metadata:
  name: dogfood-backstage
  namespace: dogfood-backstage
spec:
  selector:
    app: dogfood-backstage
  ports:
    - name: http
      port: 80
      targetPort: http