{{- $val := default dict .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  {{- range $key, $value := $val }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
