name: Helm Release

on:
  push:
    branches:
      - main
    paths:
      - 'sources/**'

jobs:
  helm-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Package and Update Charts
        run: |
          cd sources
          for dir in */ ; do
            helm dependency update "$dir"
            helm package "$dir" -d ../docs
          done
          helm repo index ../docs --url https://tetratecx.github.io/dogfood-helm
          cd ..

      - name: Commit and Push changes
        run: |
          git diff
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add docs/*
          git commit -m "Release Helm charts and update index" || echo "No changes to commit"
          git push || echo "No changes to push"
